### ISSUE TITLE
Feature Request - Add support for socket/tcp flashes

### ISSUE THREAD

**Issue by tube0013** [agners/silabs-flasher#2]
Would be great to be able to use this tool with tcp devices ;)

**Comment by Hedda** [comment]
@tube0013 FYI, noticed puddly is developing a "Universal Silicon Labs Flasher" for Silabs OTW firmware update:

https://github.com/puddly/universal-silabs-flasher

Looks like will be used in a Home Assistant Add-on for automatically flashing [SkyConnect](https://www.home-assistant.io/skyconnect/) / [Yellow](https://www.home-assistant.io/blog/2021/09/13/home-assistant-yellow/) via socat/tcp?

https://github.com/home-assistant/addons-development/pull/86

**Comment by tube0013** [comment]
universal-silabs-flasher works with socket:// 😀

**Comment by agners** [comment]
For those who don't know, universal-silabs-flasher is a much more capable flasher and available at https://github.com/NabuCasa/universal-silabs-flasher.
